# SVD decomposition with `scipy`

Import the required modules

In [1]:
import scipy.linalg as la
import numpy as np

Generate a random 5x4 matrix

In [2]:
A = np.random.rand(5,4)
A

array([[0.18951742, 0.51680403, 0.07207526, 0.2084337 ],
       [0.12837867, 0.45537122, 0.71805999, 0.69771518],
       [0.14642157, 0.02994512, 0.40046591, 0.92171258],
       [0.20635292, 0.88406125, 0.15355516, 0.96923424],
       [0.88486307, 0.84926127, 0.49064609, 0.4821183 ]])

## `<numpy|scipy>.linalg.svd` 

Equivalent implementations:
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html



### Full SVD (`full_matrices = True` - default)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [12]:
U, s, VT = np.linalg.svd(A)
#U, s, VT = la.svd(A)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 5)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [13]:
S = np.zeros(A.shape)
for i in range(len(s)):
    S[i, i] = s[i]
S

array([[2.2822113 , 0.        , 0.        , 0.        ],
       [0.        , 0.84925141, 0.        , 0.        ],
       [0.        , 0.        , 0.57382757, 0.        ],
       [0.        , 0.        , 0.        , 0.34016314],
       [0.        , 0.        , 0.        , 0.        ]])

In [14]:
S = la.diagsvd(s, A.shape[0], A.shape[1])
S

array([[2.2822113 , 0.        , 0.        , 0.        ],
       [0.        , 0.84925141, 0.        , 0.        ],
       [0.        , 0.        , 0.57382757, 0.        ],
       [0.        , 0.        , 0.        , 0.34016314],
       [0.        , 0.        , 0.        , 0.        ]])

Reconstruct the matrix $A$

In [16]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A))) # default norm is Frobenius norm

err: 7.401386e-16


### Thin SVD (`full_matrices = False`)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times q}, S \in \mathbb{R}^{q\times q}, V \in \mathbb{R}^{n\times q}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.



In [17]:
del U, s, S, VT

In [18]:
U, s, VT = la.svd(A, full_matrices = False)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 4)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [19]:
S = np.diag(s)
S

array([[2.2822113 , 0.        , 0.        , 0.        ],
       [0.        , 0.84925141, 0.        , 0.        ],
       [0.        , 0.        , 0.57382757, 0.        ],
       [0.        , 0.        , 0.        , 0.34016314]])

Reconstruct the matrix $A$

In [20]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 7.401386e-16
